### ISSUE TITLE
Provide default role

### ISSUE THREAD

**Issue by mbrueckner-kdx** [axonivy-market/cms-editor#13]
Hello Ivy Team,

Thanks a lot for providing the CMS Editor. We are very happy about this tool and its functionalities. 
After the deployment, there is only a small "thing" that we are missing: a default role.
Is it possible to add a default role to the project (not the demo version), which can be used directly after deployment to grant access to the CMS Editor?

Then it's really "ready-to-use". :-)

Thanks a lot!

**Comment by mbrueckner-kdx** [comment]
Hi @tvtphuc-axonivy,

Thx for your message. The Axon Ivy Portal Admin role is named _AXONIVY_PORTAL_ADMIN_. Well, I suggest to use _CMS_ADMIN_ to keep your formatting.

**Comment by tvtphuc-axonivy** [comment]
Thanks @mbrueckner-kdx. I will take CMS_ADMIN as role 's name

**Comment by tvtphuc-axonivy** [comment]
Hi @mbrueckner-kdx, may I ask which version of the CMS Editor you are using? Is it version 10.x.x, 11.x.x, or 12.x.x?

**Comment by mbrueckner-kdx** [comment]
Hi, the request was for 11.x, but we will use 12.x in future.

**Comment by tvtphuc-axonivy** [comment]
> Hi, the request was for 11.x, but we will use 12.x in future.

Hi @mbrueckner-kdx , can you increase the version and use version 12 ?? because the version 11 is not supported any more.

**Comment by mbrueckner-kdx** [comment]
Yes, we can and we will do it :-)

**Comment by tvtphuc-axonivy** [comment]
Hi @mbrueckner-kdx , The issue was implemented and released in version 12.0.1
![image](https://github.com/user-attachments/assets/117a74cb-a317-4540-ab5a-8e0564fa3901)
